### ISSUE TITLE
screen should never go to sleep.

### ISSUE THREAD

**Issue by darioalessandro** [security-union/remote-shutter#3]

**Comment by davidwat50** [comment]
Connection is lost  10-15 after home button is press.
I just bought video. I think I'm going to like it. I will Set it up in the house just to see how stable it is with intermittent video and standby or with interruptions like phone calls, etc.  I have two concerns which you might think about  1) Make default delay 1 sec. 2) Make it so random  motion in pocket doesn't trigger filming on or off. 3)  How much battery usage will I see over an hour or two. Can that be minimized? 4) it would be way cool of part stop cold be initiated through Apple watch on my wrist. Thanks, David - Dallas

**Comment by darioalessandro** [comment]
Hi @davidwat50 

Thanks for your feedback and we will follow up on each of the items that you mentioned!

Thanks for using Remote Shutter and happy holidays 👍

**Comment by darioalessandro** [comment]
Hi @davidwat50 today we sent an update to Apple to fix some crashes, we also added the logic to store your timer preference.

**Comment by darioalessandro** [comment]
Apple usually takes up to 5 business days to review the app, sometimes less.
